"""make canonical text nullable

Revision ID: 3d484f4a93a3
Revises: 8b924777e20b
Create Date: 2026-10-06 15:38:20.449965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d484f4a93a3'
down_revision: Union[str, Sequence[str], None] = '8b924777e20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'canonical_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'canonical_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
