"""add canonical text to documents

Revision ID: 8b924777e20b
Revises: e3966f752f91
Create Date: 2026-10-06 14:58:09.144302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b924777e20b'
down_revision: Union[str, Sequence[str], None] = 'e3966f752f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('canonical_text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'canonical_text')
    # ### end Alembic commands ###
